version: "3"
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  server:
    image: adinamitru/bookflix:latest
    tty: true
    ports:
      - "5000:5000"
    environment:
      - HOST=db
      - PORT=5000
    depends_on:
      - db
      - auth
    build: ./server

  admin:
    image: adinamitru/bookflix:admin
    tty: true
    build: ./admin
    depends_on:
      - server

  auth:
    image: auth:latest
    tty: true
    ports:
      - "6000:6000"
    environment:
      - HOST=db
      - PORT=6000
    build: ./auth
    depends_on:
      - db

  client:
    image: adinamitru/bookflix:client
    tty: true
    build: ./client
    stdin_open: true
    depends_on:
      - server

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=bookflix
      - GF_SECURITY_ADMIN_PASSWORD=bookflix


