version: "3"
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    networks:
      - network-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  server:
    image: adapter:latest
    ports:
      - "5000:5000"
    environment:
      - HOST=db
      - PORT=5000
    networks:
      - network-db
      - network-admin
      - network-client
    depends_on:
      - db
    build: ./server

  admin:
    image: adapter:latest
    build: ./admin
    depends_on:
      - server

#  server:
#    build: ./server
#    links:
#      - db
#
#  admin:
#    build: ./admin
#    links:
#      - server
#
#  client:
#    build: ./client
#    links:
#      - server
    
volumes:
  influxdb-storage:
  grafana-storage:
networks:
  network-db:
  network-admin:
  network-client:
